#!/usr/bin/env python3
#!
# mkdocs-auto
#
# TODO: One time program to setup the environment?
#
# Objectives:
# This program uses the Github hampug meetings repository for data.
# It resides in the top level of the meetings repository.
# It must be launched from the local git meetings repository 
# It requires: git, mkdocs, mkdocs-exclude, mkdocs-material
# It should be launched from a virtual environment.
#
# It performs the following:
# NO: Creates a working directory (if it doesn't already exist)
#   Off ~/ hampug-website
# NO: Clones the hampug github repository meetings
#   Off: ~/website/meetings/
# YES: This program resides in:
#   ~/.../meetings/
#   Thus it is becomes part of the repository
# NO:  But it is run from ~/hampug-website/ so the CWD is simplier to deal with
#
# Creates the mkdocs.yml that resides in ~/hampug-website/
#
# TODO: Ask Peter to fix (try to avoid empty folders):
#/nRemove list - Empty folders:
#meetings/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/
#meetings/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/
#
#Files reside in:
#meetings/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/#wekalist/ (168 files .txt.gz)
# ===

import sys
if sys.version_info[:2] < (3, 5):
    sys.exit("Please use Python 3.5 or higher.")
if sys.platform != 'linux':
    sys.exit("Please use Linux.")

import os
import glob  # Requires V3.5+
import subprocess

# Debug Flag: -d or --debug.
DEBUG = False
if "-d" in sys.argv or "--debug" in sys.argv:
    DEBUG = True

VERSION = str(0.1)
REPO_DIR = "meetings"
ORG = "Hamilton Python Users Group"
GITHUB = "https://github.com/hampug/"
URL = "https://hampug/github.io/meetings/"
SITE = "site"
# The next level up directory can have any name.
# TOP_DIR = "hampug-website"

# Force launching the program from repo directory.
# Thus level above can have any name. It will be accessed by reference.
CWD = os.getcwd()
cwd_list = CWD.split(os.sep)
if DEBUG: print("cwd:", CWD, "cwd_list[-1]:", cwd_list[-1])
if cwd_list[-1] != REPO_DIR:
    sys.exit("Program launched from: {}. \n"
             "This program should reside and be launched this from the\n" 
             "'{}' repository folder.".format(CWD, REPO_DIR))

# Get directory depth used for slicing prefix folders in mkdocs.yml:
if DEBUG: print("len(cwd_list):", len(cwd_list))
if DEBUG: print("cwd_list:" , cwd_list) 
# cwd_list: ['', 'home', 'ian', 'hampug-website', 'meetings']
DEPTH = cwd_list.index(REPO_DIR) + 1
if DEBUG: print("DEPTH:", DEPTH) # 5


# Concept: Directory constants/ variables will end with the os seperator.
cwd_list.pop()
TOP_DIR = os.sep.join(cwd_list) + os.sep
CWD = CWD + os.sep
if DEBUG: print("TOP_DIR:", TOP_DIR, "CWD:", CWD)


# If mkdocs can not reference up a dir, then need to os.chdir()
# Else in CWD is python program and mkdocs.yml. THe mkdocs.yml needs to
# have a site or docs in the TOP_DIR. Files created in TOP_DIR can be
# deleted by this program. mkdocs.yml and docs/

# Test if git exists
if glob.glob(CWD + ".git") == []:
    sys.exit("This folder, {}, is not a .git repository.".format(CWD))


#print(INTRO)

print(sys.argv)
print(os.getcwd())  # /home/ian/hampug-meetings
print(sys.argv[0])  # meetings/hampug-mkdocs
print(os.sep)  # /

#CWD = os.getcwd() + os.sep
#MEETING_DIR = CWD + REPO_DIR + os.sep

# Launch program inside of the repository meetings.
# os.chdir("..") or similar to hampug-meetings
#>>> os.getcwd()
#'/home/ian/hampug-meetings'
#>>> os.chdir("..")
#>>> os.getcwd()
#'/home/ian'

def get_readme():
    # https://www.mkyong.com/python/python-how-to-list-all-files-in-a-directory/
    # https://docs.python.org/3/library/os.html#os.walk 

    import os

    path = CWD #'/home/ian/venv7'

    files = []
    # r=root, d=directories, f = files
    for r, d, f in os.walk(path):
        for file in f:
            #if '.txt' in file:
                #files.append(os.path.join(r, file))
            files.append(os.path.join(r, file))
    for f in files:
        print(f)



def get_file_dict(path):
    """
    Files must reside off ~/.../meetings/...
    The files must have an extension.
    The absolute *path* is passed to this function. 

    Return a dictionary with each path as a key containing a list of files.

    The absolute paths are the keys. Another function will remove the prefixes 
    of the absolute paths when the navigation tree is built

    Purge from dictionary any key for a folder that has no files.

    Uses: glob module
    Requires: Python 3.5 or better

    # https://www.mkyong.com/python/python-how-to-list-all-files-in-a-directory/ 
    # https://docs.python.org/3/library/glob.html
    """
    #path = '/home/ian/venv7/'  # Requires final /
    #path = '/home/ian/hampug-meetings/'

    file_dict = {}

    # Build a dictionary of an empty list, where key is a folder path.        
    if DEBUG: print("Locating folders, build dictionary keys with empty list")
    folders = [f for f in glob.glob(path + "**/", recursive=True)]
    for folder in sorted(folders):
        if DEBUG: print(folder)
        file_dict[folder] = []

    if DEBUG: print(file_dict) # , '/home/ian/venv7/share/python-wheels/': []}
    if DEBUG: print("len(file_dict): ", len(file_dict))  # len(file_dict) : 495


    # Use the file list to add filenames to the dictionary
    if DEBUG: print("Adding files to dictionary")
    if DEBUG: print(glob.glob(path + "**/*.*", recursive=True))
    # File needs an extension to be recognised. i.e. glob *.*
    file_list = glob.glob(path + "**/*.*", recursive=True)
    for file in file_list:
        file_split = file.split("/")
        file_name = file_split.pop()
        key = "/".join(file_split)
        key = key + "/"
        if DEBUG: print(key, file_name)
        file_dict[key].append(file_name)

    if DEBUG: print(file_dict)
    if DEBUG: print("len(file_dict): ", len(file_dict))

    # Remove keys for any folders that are empty.
    # Two stages as can not remove keys when iterating over a dictionary
    remove_list = []
    for key, value in file_dict.items():
        if value == []:
            remove_list.append(key)

    if DEBUG: print(remove_list)

    print("\nWARNING: Folders contain no files. May have sub-folders:")
    for key in remove_list:
        print(key)
    print("\n")

    for key in remove_list:
        file_dict.pop(key)

    if DEBUG: print("len(file_dict): ", len(file_dict))

    for key, value in file_dict.items():
        if DEBUG: print(key, len(value))

    return file_dict


def get_markdown_files(file_dict):
    """
    Build a dictionary of the markdown files. i.e. file extension of .md
    Needs to be a list as may be more than 1 x .md in a folder.
    E.g.
    /home/ian/hampug-website/meetings/2019/ ['extra.md', 'README.md']
    """

    markdown_dict = {}
    for key, item in file_dict.items():
        for file_name in item:
            if file_name.endswith(".md"):
                if key in markdown_dict.keys():
                    # Already exists so append to list
                    markdown_dict[key].append(file_name)
                else:
                    # Create a list and append
                    markdown_dict[key] = []
                    markdown_dict[key].append(file_name)

    if DEBUG:
        for key, item in markdown_dict.items():
            #print(key, len(item))
            print(key, item, len(item))
    if DEBUG: print("len(markdown_dict):", len(markdown_dict)) # 110


    if DEBUG: print("Checking. Files that do not start with '# ':")
    count = 0
    for key, item in markdown_dict.items():
        for file_name in item:
            with open(key + file_name, "r") as fin:
                s = fin.readlines()[0]
                if s.startswith("# "):
                    #print(s) 
                    pass
                else:
                    print(key, file_name, s)
                    count += 1

    print("Total markdown files that do not start with # : {}".format(count))

    return markdown_dict

def build_navigation(markdown_dict):
    """
    NOT USED: Use auto config of nav
    What if 2 x md in same folder. Does markdown_dict work?
    Build the nav: string for use in mkdocs.yml
    Requires: markdown_dict
        DEPTH of "meetings" folder in all keys S/B: 4
    """
    s = "\nnav:\n"
    for key, item in markdown_dict.items():
        # item is a list
        key_list = key.split(os.sep)
        if DEBUG: print(key_list)
        # ['', 'home', 'ian', 'hampug-website', 'meetings', '2019', '']

        key_list = key_list[DEPTH:]
        key_indent = len(key_list)
        if DEBUG: print(key_list) # ['2019', '']
        key_short = os.sep.join(key_list)
        if DEBUG: print(key_short) # 2019/
        for file_name in item:
            with open(key + file_name, "r") as fin:
                title = fin.readlines()[0]
                title = title[2:]  # Strip the '# '
                title = title.strip() # Strip the n/l and trailing spaces
    
            path = key_short + file_name
            if DEBUG: print(path) # 2019/README.md
            prefix = " " * key_indent * 4 + "- "
            path = ": '"+ path + "'"
            if DEBUG: print(prefix + title + path)
            s += prefix + title + path + "\n"

            #nav:
            #    - About: 'about.md'
            #    - Meetings: 'README.md'
            #        - 2014: '2014/README.md'
            #            - 2014-02-24: '2014/2014-02-24/README.md'
            #            - 2014-03-10: '2014/2014-03-10/README.md'
            #            - 2014-04-14: '2014/2014-04-14/README.md'
            #            - 2014-05-12: '2014/2014-05-12/README.md'
            #            - 2014-06-09: '2014/2014-06-09/README.md'
            #                - Spyder: '2014/2014-06-09/spyderlib/README.md'
 
            #['', 'home', 'ian', 'hampug-website', 'meetings', '2019', '']
            #['2019', '']
            #2019/
            #2019/extra.md
            #    -: '2019/extra.md'
            #2019/README.md
            #    -: '2019/README.md'
    s += "\n"
    if DEBUG: print(s)
    return s
        
def run_mkdocs(mkdocs_file):
    """
    MkDocs is run up-one-level (TOP_DIR) from CWD, so it finds its folders OK.
    Create the file mkdocs.yml up-one-level
    If folder doesn't exist may need to create docs/ up-one-level
    """
    with open(TOP_DIR + "mkdocs.yml", "w") as fout:
        fout.write(mkdocs_file)

    # Remove contents of docs
    # 
    command = "rm -r docs/*"
    completed = subprocess.run(command, shell=True)
    print('returncode:', completed.returncode)
    

    # run mkdocs built --clean up one level
    print("os.getcwd():", os.getcwd())
    # Go up one directory to run the mkdocs
    os.chdir("..")
    #os.path.normpath(os.getcwd() + os.sep + os.pardir)
    print("os.getcwd():", os.getcwd())

    #command = 'ls .. -1'  # < -- Works
    # Run mkdocs
    command = "mkdocs build --clean"
    completed = subprocess.run(command, shell=True)
    print('returncode:', completed.returncode)

    os.chdir("meetings")
    print("os.getcwd():", os.getcwd())   

    # Check if want to continue.
    prompt = "About to proceed with git update. Do you want to continue? [Y/n]: "
    response = input(prompt)
    if response == "":
        response = "y"
    if response[0].lower() not in ("y", "t", 1):
        sys.exit("Exiting...")

    command = "rsync -r ../docs/ docs/"
    completed = subprocess.run(command, shell=True)
    print('returncode:', completed.returncode)

    command = "git status"
    completed = subprocess.run(command, shell=True)
    print('returncode:', completed.returncode)

    command = "git add --all"
    completed = subprocess.run(command, shell=True)
    print('returncode:', completed.returncode)

    command = "git commit -m 'update website'"
    completed = subprocess.run(command, shell=True)
    print('returncode:', completed.returncode)

    command = "git push -u origin master"
    completed = subprocess.run(command, shell=True)
    print('returncode:', completed.returncode)

    """
    (venv7) ian@X200:~/hampug-website/meetings$ pwd; cd ..; pwd; date; cd meetings; pwd
    /home/ian/hampug-website/meetings
    /home/ian/hampug-website
    Sun Sep  8 10:03:49 NZST 2019
    /home/ian/hampug-website/meetings

    > doit = subprocess.Popen('here.exe -command', cwd='C:/myproject/betty/')

    In Python use import os then os.chdir('/tmp/yourdirectory') That will set the current directory for your python script. 
    >>> os.getcwd()
    '/home/ian/knife1/Spoon-Knife'

    >>> os.chdir("..")
    >>> os.getcwd()
    '/home/ian/knife1'

    # Go up one directory
    os.path.normpath(os.getcwd() + os.sep + os.pardir)
    """

    #command = ['cd ..' ]
    #completed = subprocess.run(command)
    #print('returncode:', completed.returncode)          

    #command = ['ls', '-1']
    #completed = subprocess.run(command)
    #print('returncode:', completed.returncode)  

def create_data():
    # In the meetings folder create mock data
    pass
        

def program_info():
    """
    Provide some information on program launch.
    """
    print("Python3 program: {}".format(sys.argv[0]))
    print("Version: {}".format(VERSION))
    print("Launched from: {}".format(CWD))
    print("Contains .git repository: {}".format(os.path.isdir(CWD + ".git")))


    #dir_list = CWD.split("/")
    # print(len(dir_list), dir_list, dir_list[-2])
    # 5 ['', 'home', 'ian', 'hampug-meetings', ''] hampug-meetings
    #if dir_list[-2] != LAUNCH_DIR:
    #    sys.exit("Please run this python program from: {}".format(LAUNCH_DIR))
    #print("Meetings respository: {}".format(MEETING_DIR))

    #print(os.path.isfile("/home/ian/hampug-meetings/meetings/mkdocs-auto"))
    #print(os.path.isdir("/home/ian/hampug-meetings/meetings/.git"))

def help():
    if "-h" in sys.argv or "--help" in sys.argv:
        print(INTRO)


def main():
    help()

    program_info()

    #get_readme()
    #file_dict = get_file_dict('/home/ian/venv7/')


    # Get a dictionary of all files in 
    file_dict = get_file_dict(CWD)
    #file_dict = get_file_dict('/home/ian/hampug-meetings/')

    for key, value in file_dict.items():
        if DEBUG: print(key, len(value))

    # len(file_dict):  147
    # len(file_dict):  138  # 9 empty folders:

    markdown_dict = get_markdown_files(file_dict)

    # OK to here 110 .md files all start with # 
    # TODO: Build the nav path
    nav_string = build_navigation(markdown_dict)
    if DEBUG: print(nav_string)

    #  nav: string not required auto-generated.
    mkdocs_file = TEMPLATE  #  + nav_string
    if DEBUG: print(mkdocs_file)

    run_mkdocs(mkdocs_file)

    sys.exit()

    #get_glob_short_path()
    filter_prefix = "/home/ian/"
    filter_prefix = '/home/ian/hampug-meetings/'
    #filter_prefix = '/home/ian/venv7/'  
    build_nav(file_dict, filter_prefix)
    #build_nav(file_dict)


    pass

# Stuff long-winded constants here...
# The template for building the mkdocs.yml file
TEMPLATE = """site_name: HamPUG
docs_dir: meetings  # Source files. default is docs
site_dir: docs      # Website files. (Temporary): Default is site.
                    # Website files are later rsync'ed to meetings/docs

# The material theme uses a different search from the default mkdocs theme
theme: 
    name: 'material'  # was 'mkdocs'
    palette:
        primary: 'indigo'
        accent: 'indigo'

# Exclude plugin: https://github.com/apenwarr/mkdocs-exclude
# Exclude the /docs/ folder (the website) in the meetings source folder
# Since meetings is the source, then just need doc/* to exclude
# This is later used to hold the website via:
# rsync -r docs/ meetings/docs/ 
# Exclude: 
#   Impress presentation files (.opd) 
#   Jupyter Notebook (.ipynb)
# '- search' needs to be added to the plugins list.

plugins:
    - exclude:
        glob:
            - docs/* 
            - "*.odp"
            - "*.ipynb"
            - "*.yml"
            - about.md
    - search:

"""

INTRO = """
Welcome to the program '{}' version {}.
This program is for creating a Github project website for:
{}.
Their Github account is: {}
The specific repository is: '{}'.
The created website will have the URL: {}

It is assumed that the current document layout on Github is in a sorted 
fashion. The website navigation will be based on a sort of the Github
repository. 

A requirement is that all markdown documents commence the first
line with a single hash, '#', and space, followed by a brief title. This
title is used in the website navigation.

This program assumes that you have a local git repository called '{}'
and that this program is being run from that repository. For example your
local folders may be ~/hampug-website/meetings/

Prerequisites:
0. This program is already in the top level Github meetings repository.
1. Run this program from a virtual environment which includes:
    o Python3.5 or higher.
    o mkdocs version 1.0.4 or higher.
    o mkdocs-exclude 1.0.2 or higher. Plugin to exclude files or folders.
    o mkdocs-material 4.4.2 or higher. Theme plugin
    o git version 2.17.1 or higher.
2. In the {} Github repository {} 'Clone or Download' the repository so that 
    it becomes one of your Github repositories.
3. Create a local folder. E.g. $ mkdir github-website
4. Change directory to that folder. E.g. $ cd github-website
5. Clone Github to the local directory
    $ git cloan https://github.com/MY_GITHUB_ACCOUNT/{}.git
    This will create the folder {} which will be a git repository with a .git
    folder off it.
6. Set default to meetings. E.g. cd meetings.
7. Run this program. From this meetings directory.
8. The mkdocs.yml file and the /docs folder containing the website are placed
    into the directory above meetings.
9. Execute mkdocs commands from this directory as follows:
    (venv) ian:~/website/meetings$ cd .. ; mkdocs build ; cd meetings
    INFO    -  Cleaning site directory 
    INFO    -  Building documentation to directory: /home/ian/meetings/docs 

The program will do the following: 
1. Review the '{}' repository and locate all markdown files.
2. Check all markdown files meet the 'first line' requirement.
3. Build the nav: structure.
4. Build mkdocs.yml which will be placed folder up one level in: {}.
5. Up one level create the folder for the website: {}
6. Second line requirment is "Links: github" 
7. Run mkdocs to build the website
8. Run rsync to move the website into the respository off the /docs folder

When the program terminates you may then:
1. Test the website with mkdocs serve
2. Push the .git repository to Github. The changes will be the /docs folder.
3. Test the updated website at: {}
""".format(sys.argv[0], VERSION, ORG, GITHUB, REPO_DIR, URL, REPO_DIR, 
GITHUB, REPO_DIR, REPO_DIR, REPO_DIR, REPO_DIR, TOP_DIR, SITE, URL)


if __name__=="__main__":
    main()


"""
Notes:
https://docs.python.org/3/library/glob.html
>>> import glob
>>> dir(glob)
['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_glob0', '_glob1', '_glob2', '_iglob', '_ishidden', '_isrecursive', '_iterdir', '_rlistdir', 'escape', 'fnmatch', 'glob', 'glob0', 'glob1', 'has_magic', 'iglob', 'magic_check', 'magic_check_bytes', 'os', 're']
>>> 

If recursive is true, the pattern “**” will match any files and zero or more directories and subdirectories. If the pattern is followed by an os.sep, only directories and subdirectories match.
Changed in version 3.5: Support for recursive globs using “**”.



https://stackoverflow.com/questions/3964681/find-all-files-in-a-directory-with-extension-txt-in-python

You can use glob:

import glob, os
os.chdir("/mydir")
for file in glob.glob("*.txt"):
    print(file)

or simply os.listdir:

import os
for file in os.listdir("/mydir"):
    if file.endswith(".txt"):
        print(os.path.join("/mydir", file))

or if you want to traverse directory, use os.walk:

import os
for root, dirs, files in os.walk("/mydir"):
    for file in files:
        if file.endswith(".txt"):
             print(os.path.join(root, file))


for file in [f for f in os.listdir('/mydir') if f.endswith('.txt')]:


>>> a["test"] = None
>>> a
{'test': None}
>>> type a[test]
  File "<stdin>", line 1
    type a[test]
         ^
SyntaxError: invalid syntax
>>> type a["test"]
  File "<stdin>", line 1
    type a["test"]
         ^
SyntaxError: invalid syntax
>>> type(a["test"])
<class 'NoneType'>

{
'/home/ian/venv7/': [
    'pyvenv.cfg'
    ], 
'/home/ian/venv7/bin/': [
    'activate.fish', 
    'activate.csh', 
    'pip3.6', 
...

'/home/ian/venv7/share/': [
    ], 
'/home/ian/venv7/share/python-wheels/': [
    'pip-9.0.1-py2.py3-none-any.whl', 
    'webencodings-0.5-py2.py3-none-any.whl', 
    'appdirs-1.4.3-py2.py3-none-any.whl', 
    'pyparsing-2.2.0-py2.py3-none-any.whl', 
    'certifi-2018.1.18-py2.py3-none-any.whl', 
....
    'CacheControl-0.11.7-py2.py3-none-any.whl', 
    'distro-1.0.1-py2.py3-none-any.whl', 
    'wheel-0.30.0-py2.py3-none-any.whl'
    ]
}


    print("Files:")
    print(glob.glob(path + "**/*.*", recursive=True))
    file_list = glob.glob(path + "**/*.*", recursive=True)
    for file in file_list:
        print(file)

=====

def get_glob_short_path():
    import glob
    path = '/home/ian/venv7/'  # Requires final /
    #path = '/home/ian/hampug-meetings/'

    file_dict = {}
    print("Folders:")
    folders = [f for f in glob.glob(path + "**/", recursive=True)]
    for folder in sorted(folders):
        #print(folder)
        folder_list = folder.split("/")
        # Remove the '/home/ian/venv7/'
        #for i in range(4):
        #    folder_list.pop(0)
        # mylist = mylist[2:-2] and del mylist[:2];del mylist[-2:]
        # Do 4 x pop(0)'s
        folder_list = folder_list[4:]    

        folder = "/".join(folder_list)
        #folder = folder + "/"
        # Build a dictionary of empty lists
        file_dict[folder] = []
    print(file_dict) # 'share/': [], 'share/python-wheels/': []}
    # was: # , '/home/ian/venv7/share/python-wheels/': []}
    # key is suitable for going into mkdocs.yml
    print("len(file_dict) :", len(file_dict))  # len(file_dict) : 495

    for key, item in file_dict.items():
        print(key, item)
        #lib64/python3.6/site-packages/yaml/__pycache__/
        #share/
        #share/python-wheels/

    print("Files:")
    #print(glob.glob(path + "**/*.*", recursive=True))
    file_list = glob.glob(path + "**/*.*", recursive=True)
    for file in sorted(file_list):
        file_split = file.split("/")
        file_name = file_split.pop()
        file_key = file_split[4:]  # Remove the prefix folders
        key = "/".join(file_key)
        key = key + "/"
         
        #print(key, file_name)
        # With shortened names can not have a key of "/"
        if key == "/":
            print(key, file_name)  # / pyvenv.cfg


        if key != "/":
            file_dict[key].append(file_name)
    #file_dict['share/python-wheels/'].append('x')
    #file_dict['share/python-wheels/'].append(file_name)
    #print(file_dict['share/python-wheels/'])

    #print(file_dict)
    #for key, item in file_dict.items():
    #    print(key, item)
    
    #print(file_dict["/"])
    
#def get_glob():


=====
"""



"""



#files = [f for f in glob.glob(path + "**/*.txt", recursive=True)]
files = [f for f in glob.glob(path + "**/*.*", recursive=True)]

for f in files:
    #print(f)
    pass

===

(venv7) ian@X200:~$ cd knife1
(venv7) ian@X200:~/knife1$ 
(venv7) ian@X200:~/knife1$ 
(venv7) ian@X200:~/knife1$ ls -la
total 8
drwxrwxr-x  2 ian ian 4096 Sep  5 17:19 .
drwxr-xr-x 98 ian ian 4096 Sep  5 17:19 ..
(venv7) ian@X200:~/knife1$ git clone https://github.com/irsbugs/Spoon-Knife.git
Cloning into 'Spoon-Knife'...
remote: Enumerating objects: 16, done.
remote: Total 16 (delta 0), reused 0 (delta 0), pack-reused 16
Unpacking objects: 100% (16/16), done.
(venv7) ian@X200:~/knife1$ ls -lA
total 4
drwxrwxr-x 3 ian ian 4096 Sep  5 17:20 Spoon-Knife
(venv7) ian@X200:~/knife1$ 


drwxrwxr-x 3 ian ian 4096 Sep  5 17:20 Spoon-Knife
(venv7) ian@X200:~/knife1$ ls -lA Spoon-Knife/
total 16
drwxrwxr-x 8 ian ian 4096 Sep  5 17:20 .git
-rw-rw-r-- 1 ian ian  355 Sep  5 17:20 index.html
-rw-rw-r-- 1 ian ian  780 Sep  5 17:20 README.md
-rw-rw-r-- 1 ian ian  256 Sep  5 17:20 styles.css


===


/nRemove list - Empty folders:
/home/ian/hampug-website/meetings/2014/
/home/ian/hampug-website/meetings/2015/
/home/ian/hampug-website/meetings/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/
/home/ian/hampug-website/meetings/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/
/home/ian/hampug-website/meetings/2016/
/home/ian/hampug-website/meetings/2017/
/home/ian/hampug-website/meetings/2017/2017-05-08/ian/
/home/ian/hampug-website/meetings/2018/
/home/ian/hampug-website/meetings/2019/


Fixed folders for 2017/2017-05-08/ian/

/nRemove list - Empty folders:
/home/ian/hampug-website/meetings/2014/
/home/ian/hampug-website/meetings/2015/
/home/ian/hampug-website/meetings/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/
/home/ian/hampug-website/meetings/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/
/home/ian/hampug-website/meetings/2016/
/home/ian/hampug-website/meetings/2017/
/home/ian/hampug-website/meetings/2018/
/home/ian/hampug-website/meetings/2019/


====

Fix /home/ian/hampug-website/meetings/2017/2017-05-08/ian/

(venv7) ian@X200:~/hampug-website/meetings$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   2017/2017-05-08/README.md
	deleted:    2017/2017-05-08/ian/client_server/README.md
	deleted:    2017/2017-05-08/ian/client_server/client_server_presentation.odp
	deleted:    2017/2017-05-08/ian/client_server/gtk_client.py
	deleted:    2017/2017-05-08/ian/client_server/server.py
	deleted:    2017/2017-05-08/ian/google_talk/README.md
	deleted:    2017/2017-05-08/ian/google_talk/google_talk_presentation.tar.gz
	modified:   mkdocs-auto

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	2017/2017-05-08/ian-client-server/
	2017/2017-05-08/ian-google-talk/

no changes added to commit (use "git add" and/or "git commit -a")
(venv7) ian@X200:~/hampug-website/meetings$ git add --all
(venv7) ian@X200:~/hampug-website/meetings$ git commit -m "correct paths"
[master 80a56c6] correct paths
 8 files changed, 21 insertions(+), 5 deletions(-)
 rename 2017/2017-05-08/{ian/client_server => ian-client-server}/README.md (100%)
 rename 2017/2017-05-08/{ian/client_server => ian-client-server}/client_server_presentation.odp (100%)
 rename 2017/2017-05-08/{ian/client_server => ian-client-server}/gtk_client.py (100%)
 rename 2017/2017-05-08/{ian/client_server => ian-client-server}/server.py (100%)
 rename 2017/2017-05-08/{ian/google_talk => ian-google-talk}/README.md (100%)
 rename 2017/2017-05-08/{ian/google_talk => ian-google-talk}/google_talk_presentation.tar.gz (100%)
(venv7) ian@X200:~/hampug-website/meetings$ git push -u origin master
Username for 'https://github.com': irsbugs
Password for 'https://irsbugs@github.com': 
Counting objects: 6, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 866 bytes | 866.00 KiB/s, done.
Total 6 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/irsbugs/meetings.git
   3e7a592..80a56c6  master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
(venv7) ian@X200:~/hampug-website/meetings$ 

===

(venv7) ian@X200:~/hampug-website/meetings$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	2014/README.md
	2015/README.md
	2016/README.md
	2017/README.md
	2018/README.md
	2019/README.md

nothing added to commit but untracked files present (use "git add" to track)
(venv7) ian@X200:~/hampug-website/meetings$ 

(venv7) ian@X200:~/hampug-website/meetings$ git add --all
(venv7) ian@X200:~/hampug-website/meetings$ git commit -m "add year summary"
[master 6d26605] add year summary
 6 files changed, 86 insertions(+)
 create mode 100644 2014/README.md
 create mode 100644 2015/README.md
 create mode 100644 2016/README.md
 create mode 100644 2017/README.md
 create mode 100644 2018/README.md
 create mode 100644 2019/README.md
(venv7) ian@X200:~/hampug-website/meetings$ git push -u origin master
Username for 'https://github.com': irsbugs
Password for 'https://irsbugs@github.com': 
Counting objects: 14, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (14/14), done.
Writing objects: 100% (14/14), 1.70 KiB | 871.00 KiB/s, done.
Total 14 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
To https://github.com/irsbugs/meetings.git
   80a56c6..6d26605  master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
(venv7) ian@X200:~/hampug-website/meetings$ 

===

TODO: Ask Peter to fix:

/nRemove list - Empty folders:
meetings/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/
meetings/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/

Files reside in:
meetings/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/ (168 files .txt.gz)

===

To be fixed: md files that don't start with '# '

/home/ian/hampug-website/meetings/ README.md meetings

/home/ian/hampug-website/meetings/2014/2014-06-09/spyderlib/ README.md Spyder - first impressions

/home/ian/hampug-website/meetings/2014/2014-10-13/diy_home_monitoring/ README.md DIY Home Monitoring

/home/ian/hampug-website/meetings/2014/2014-10-13/gooey/ README.md Gooey

/home/ian/hampug-website/meetings/2014/2014-12-08/datamining/ README.md README

/home/ian/hampug-website/meetings/2015/2015-04-13/libreoffice/ README.md LibreOffice and Python

/home/ian/hampug-website/meetings/2015/2015-05-11/libreoffice/ README.md Python + LibreOffice

/home/ian/hampug-website/meetings/2015/2015-05-11/libreoffice/python version minimum/ README.md Python Version Minimum

/home/ian/hampug-website/meetings/2015/2015-05-11/libreoffice/pythonhouse/ README.md Python Universal Network Object (UNO) Bridge to LibreOffice/OpenOffice

/home/ian/hampug-website/meetings/2015/2015-05-11/matplotlib/ README.md Plotting using matplotlib

/home/ian/hampug-website/meetings/2015/2015-10-12/begins/ README.md begins

/home/ian/hampug-website/meetings/2015/2015-10-12/plac/ README.md Plac presentation

/home/ian/hampug-website/meetings/2015/2015-10-12/quiz/ README.md Quiz presentation

/home/ian/hampug-website/meetings/2015/2015-10-12/sys.argv/ README.md Sys module presentation

/home/ian/hampug-website/meetings/2016/2016-04-11/ncea presentation/ README.md NCEA

/home/ian/hampug-website/meetings/2016/2016-04-11/prime_number/ README.md Prime number

/home/ian/hampug-website/meetings/2016/2016-05-09/python2to3experiences/ python2to3migration.md Python 2.7 to 3 migration

/home/ian/hampug-website/meetings/2016/2016-11-14/web2py/ README.md web2py + meetup.com

/home/ian/hampug-website/meetings/2017/2017-04-10/ian/ README.md ## Flask ##

/home/ian/hampug-website/meetings/2017/2017-05-08/ian-client-server/ README.md ## Client Server Presentation

/home/ian/hampug-website/meetings/2017/2017-05-08/ian-google-talk/ README.md ## Google Text to Speech

/home/ian/hampug-website/meetings/2017/2017-10-09/ian/ README.md ## The Cycle Analyst and Capturing its Serial Line data with Asyncio

/home/ian/hampug-website/meetings/2018/2018-03-12/ian/ README.md ### Setting up Python on Windows x64

/home/ian/hampug-website/meetings/2018/2018-05-14/ian/ README.md ## Installation of Jupyter Notebook

/home/ian/hampug-website/meetings/2018/2018-10-08/fifo/ README.md ### String data manipulation using list methods

/home/ian/hampug-website/meetings/2019/2019-03-11/local_bin/ README.md ## A Local /bin Directory

/home/ian/hampug-website/meetings/2019/2019-06-10/ian/ README.md There are sets of line drawing characters. They reside in the range from 9480 through 9628. 

  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   2014/2014-06-09/spyderlib/README.md
	modified:   2014/2014-10-13/diy_home_monitoring/README.md
	modified:   2014/2014-10-13/gooey/README.md
	modified:   2014/2014-12-08/datamining/README.md
	modified:   2015/2015-04-13/libreoffice/README.md
	modified:   2015/2015-05-11/libreoffice/README.md
	modified:   2015/2015-05-11/libreoffice/python version minimum/README.md
	modified:   2015/2015-05-11/libreoffice/pythonhouse/README.md
	modified:   2015/2015-05-11/matplotlib/README.md
	modified:   2015/2015-10-12/begins/README.md
	modified:   2015/2015-10-12/plac/README.md
	modified:   2015/2015-10-12/quiz/README.md
	modified:   2015/2015-10-12/sys.argv/README.md
	modified:   2016/2016-04-11/ncea presentation/README.md
	modified:   2016/2016-04-11/prime_number/README.md
	modified:   2016/2016-05-09/python2to3experiences/python2to3migration.md
	modified:   2016/2016-11-14/web2py/README.md
	modified:   2017/2017-04-10/ian/README.md
	modified:   2017/2017-05-08/ian-client-server/README.md
	modified:   2017/2017-05-08/ian-google-talk/README.md
	modified:   2017/2017-10-09/ian/README.md
	modified:   2018/2018-03-12/ian/README.md
	deleted:    2018/2018-05-14/ian/Jupyter Notebook Install.odp
	deleted:    2018/2018-05-14/ian/Python Version Check.odp
	deleted:    2018/2018-05-14/ian/README.md
	modified:   2018/2018-10-08/fifo/README.md
	modified:   2019/2019-03-11/local_bin/README.md
	modified:   2019/2019-06-10/ian/README.md
	modified:   README.md
	modified:   mkdocs-auto

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	2018/2018-05-14/ian-jupiter/
	2018/2018-05-14/ian-python-version/

no changes added to commit (use "git add" and/or "git commit -a")


====

OLD NOT USED

#def build_nav(file_dict, filter_prefix):
def build_nav(file_dict, filter_prefix = os.getcwd()):
    '''
    Use the file_dict to build the mkdocs.yml nav: paths
    Files in the top level are changed to use their file name
    Except that README.md in top level will become index.html 

    '''
    #if filter_prefix == "":
    #    filter_prefix = os.getcwd()

    if DEBUG: print("filter_prefix: ", filter_prefix)
    if DEBUG: print("len(file_dict): ", len(file_dict))
    for key, file_name_list in sorted(file_dict.items()):

        key_short = key.replace(filter_prefix,'')
        for file_name in file_name_list: 
            if file_name == "README.md":
                # Check first line of README.md for a Title
                with open(key + file_name) as f:
                    first_line = f.readline().strip()
                    first_line_list = first_line.split(" ")
                    print(first_line_list[1])  # About
        


            path = key_short + file_name

        #y = x.replace('.good','')
        print(key_short, path) # /meetings/ /meetings/README.md


    #     path = '/home/ian/venv7/' 
    # The initial path is 3 x folders: Remove the first three folders
    # from the key
    #file_split.pop(0)
    #file_split.pop(0)
    #file_split.pop(0)



(venv7) ian@X200:~/hampug-website/meetings$ cd .. ; mkdocs build ; cd meetings
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/ian/hampug-website/docs 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - README.md
  - about.md
  - 2014/README.md
  - 2015/2015-05-11/README.md
  - 2015/2015-05-11/libreoffice/README.md
  - 2015/2015-05-11/libreoffice/python version minimum/README.md
  - 2015/2015-05-11/libreoffice/pythonhouse/README.md
  - 2015/2015-05-11/matplotlib/README.md
  - 2015/2015-06-08/README.md
  - 2015/2015-07-13/README.md
  - 2015/2015-08-10/README.md
  - 2015/2015-09-14/README.md
  - 2015/2015-10-12/README.md
  - 2015/2015-10-12/begins/README.md
  - 2015/2015-10-12/plac/README.md
  - 2015/2015-10-12/quiz/README.md
  - 2015/2015-10-12/sys.argv/README.md
  - 2015/2015-11-09/README.md
  - 2015/2015-11-09/pelican/Pelican.md
  - 2015/2015-11-09/pyudev/README.md
  - 2015/2015-12-14/README.md
  - 2016/README.md
  - 2016/2016-02-08/README.md
  - 2016/2016-03-14/README.md
  - 2016/2016-04-11/README.md
  - 2016/2016-04-11/ncea presentation/README.md
  - 2016/2016-04-11/prime_number/README.md
  - 2016/2016-05-09/README.md
  - 2016/2016-05-09/python2to3experiences/python2to3migration.md
  - 2016/2016-06-13/README.md
  - 2016/2016-07-11/README.md
  - 2016/2016-08-08/README.md
  - 2016/2016-09-12/README.md
  - 2016/2016-09-12/ian-python_art/README.md
  - 2016/2016-09-12/ian-tkinter_templates/README.md
  - 2016/2016-10-10/README.md
  - 2016/2016-11-14/README.md
  - 2016/2016-11-14/web2py/README.md
  - 2016/2016-12-13/README.md
  - 2017/README.md
  - 2017/2017-02-13/README.md
  - 2017/2017-03-13/README.md
  - 2017/2017-04-10/README.md
  - 2017/2017-04-10/ian/README.md
  - 2017/2017-05-08/README.md
  - 2017/2017-05-08/ian-client-server/README.md
  - 2017/2017-05-08/ian-google-talk/README.md
  - 2017/2017-06-12/README.md
  - 2017/2017-07-10/README.md
  - 2017/2017-08-10/README.md
  - 2017/2017-09-11/README.md
  - 2017/2017-10-09/README.md
  - 2017/2017-10-09/ian/README.md
  - 2017/2017-11-13/README.md
  - 2017/2017-12-11/README.md
  - 2018/README.md
  - 2018/2018-02-12/README.md
  - 2018/2018-03-12/README.md
  - 2018/2018-03-12/ian/README.md
  - 2018/2018-04-09/README.md
  - 2018/2018-05-14/README.md
  - 2018/2018-05-14/ian-jupiter/README.md
  - 2018/2018-05-14/ian-python-version/README.md
  - 2018/2018-05-14/my_first_notebook/README.md
  - 2018/2018-06-11/README.md
  - 2018/2018-06-11/presentation.md
  - 2018/2018-07-09/README.md
  - 2018/2018-08-13/README.md
  - 2018/2018-09-10/README.md
  - 2018/2018-09-10/waitress/README.md
  - 2018/2018-10-08/README.md
  - 2018/2018-10-08/fifo/README.md
  - 2018/2018-11-12/README.md
  - 2018/2018-12-10/README.md
  - 2019/README.md
  - 2019/extra.md
  - 2019/2019-02-11/README.md
  - 2019/2019-03-11/README.md
  - 2019/2019-03-11/local_bin/README.md
  - 2019/2019-03-11/rpi3_and_tensorflow/README.md
  - 2019/2019-04-08/README.md
  - 2019/2019-05-13/README.md
  - 2019/2019-06-10/README.md
  - 2019/2019-06-10/bonobo/README.md
  - 2019/2019-06-10/bubbles/README.md
  - 2019/2019-06-10/data/README.md
  - 2019/2019-06-10/ian/README.md
  - 2019/2019-06-10/pandas/README.md
  - 2019/2019-06-10/petl/README.md
  - 2019/2019-07-08/README.md
  - 2019/2019-07-08/jupyter_kernels/README.md
  - 2019/2019-07-08/pep484_type_hinting/README.md
  - 2019/2019-08-12/README.md 


Last bit of updating...

os.getcwd(): /home/ian/hampug-website/meetings
os.getcwd(): /home/ian/hampug-website
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/ian/hampug-website/docs 
returncode: 0
os.getcwd(): /home/ian/hampug-website/meetings
returncode: 0
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   mkdocs-auto

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	docs/

no changes added to commit (use "git add" and/or "git commit -a")
returncode: 0
returncode: 0
[master bc28c71] update website
 485 files changed, 229588 insertions(+), 1 deletion(-)
 create mode 100644 docs/2014/2014-02-24/index.html
 create mode 100644 docs/2014/2014-03-10/index.html
 create mode 100644 docs/2014/2014-04-14/files/create-cloud.R
 create mode 100644 docs/2014/2014-04-14/files/final-output.png
 create mode 100644 docs/2014/2014-04-14/files/get.py
 create mode 100644 docs/2014/2014-04-14/files/out/out.txt
 create mode 100644 docs/2014/2014-04-14/files/wordle.pdf
 create mode 100644 docs/2014/2014-04-14/index.html
 create mode 100644 docs/2014/2014-05-12/index.html
 create mode 100644 docs/2014/2014-06-09/Eric Circle Presentation - Code.tar.gz
 create mode 100644 docs/2014/2014-06-09/index.html
 create mode 100644 docs/2014/2014-06-09/spyderlib/index.html
 create mode 100644 docs/2014/2014-06-09/spyderlib/screenshot.png
 create mode 100644 docs/2014/2014-07-14/index.html
 create mode 100644 docs/2014/2014-08-18/PyFunk.tar.gz
 create mode 100644 docs/2014/2014-08-18/index.html
 create mode 100644 docs/2014/2014-09-08/index.html
 create mode 100644 docs/2014/2014-10-13/diy_home_monitoring/20141013-182459.jpg
 create mode 100644 docs/2014/2014-10-13/diy_home_monitoring/20141013-182500.jpg
 create mode 100644 docs/2014/2014-10-13/diy_home_monitoring/20141013-182501.jpg
 create mode 100644 docs/2014/2014-10-13/diy_home_monitoring/examples.py
 create mode 100644 docs/2014/2014-10-13/diy_home_monitoring/index.html
 create mode 100644 docs/2014/2014-10-13/gooey/gooey-rand/gooey-rand.py
 create mode 100644 docs/2014/2014-10-13/gooey/index.html
 create mode 100644 docs/2014/2014-10-13/index.html
 create mode 100644 docs/2014/2014-11-10/index.html
 create mode 100644 docs/2014/2014-12-08/datamining/2013-December.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/2014-April.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/2014-August.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/2014-February.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/2014-January.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/2014-July.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/2014-June.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/2014-March.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/2014-May.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/2014-November.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/2014-October.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/2014-September.txt.gz
 create mode 100644 docs/2014/2014-12-08/datamining/index.html
 create mode 100644 docs/2014/2014-12-08/datamining/list.flow
 create mode 100644 docs/2014/2014-12-08/datamining/list.py
 create mode 100644 docs/2014/2014-12-08/hangman/hangman_no_set.py
 create mode 100644 docs/2014/2014-12-08/hangman/hangman_set.py
 create mode 100644 docs/2014/2014-12-08/index.html
 create mode 100644 docs/2014/index.html
 create mode 100644 docs/2015/2015-02-09/Testing.otp
 create mode 100644 docs/2015/2015-02-09/index.html
 create mode 100644 docs/2015/2015-03-09/index.html
 create mode 100644 docs/2015/2015-03-09/notes.txt
 create mode 100644 docs/2015/2015-04-13/index.html
 create mode 100644 docs/2015/2015-04-13/libreoffice/index.html
 create mode 100644 docs/2015/2015-04-13/libreoffice/pushbuttontime files/pushbutton.py
 create mode 100644 docs/2015/2015-04-13/libreoffice/pushbuttontime files/pushbuttontime.odg
 create mode 100644 docs/2015/2015-04-13/libreoffice/pushbuttontime files/pushbuttontimedoc.odg
 create mode 100644 docs/2015/2015-04-13/libreoffice/pushbuttontime files/pushbuttontimedoc_embeddedpy.odg
 create mode 100644 docs/2015/2015-04-13/libreoffice/pushbuttontime files/pushbuttontimesys.odg
 create mode 100644 docs/2015/2015-04-13/libreoffice/pyinsert.py
 create mode 100644 docs/2015/2015-04-13/libreoffice/user2document.py
 create mode 100644 docs/2015/2015-05-11/index.html
 create mode 100644 docs/2015/2015-05-11/libreoffice/index.html
 create mode 100644 docs/2015/2015-05-11/libreoffice/python version minimum/demo files/python_demo1.py
 create mode 100644 docs/2015/2015-05-11/libreoffice/python version minimum/demo files/python_demo2.py
 create mode 100644 docs/2015/2015-05-11/libreoffice/python version minimum/demo files/python_demo3.py
 create mode 100644 docs/2015/2015-05-11/libreoffice/python version minimum/demo files/python_demo4.py
 create mode 100644 docs/2015/2015-05-11/libreoffice/python version minimum/index.html
 create mode 100644 docs/2015/2015-05-11/libreoffice/pythonhouse/index.html
 create mode 100644 docs/2015/2015-05-11/libreoffice/pythonhouse/pythonhouse.py
 create mode 100644 docs/2015/2015-05-11/matplotlib/index.html
 create mode 100644 docs/2015/2015-05-11/matplotlib/scatterplots/bodyfat.csv
 create mode 100644 docs/2015/2015-05-11/matplotlib/scatterplots/bolts.csv
 create mode 100644 docs/2015/2015-05-11/matplotlib/scatterplots/scatter1.py
 create mode 100644 docs/2015/2015-05-11/matplotlib/scatterplots/scatter2.py
 create mode 100644 docs/2015/2015-05-11/matplotlib/scatterplots/scatter3.py
 create mode 100644 docs/2015/2015-05-11/matplotlib/scatterplots/slug.README
 create mode 100644 docs/2015/2015-05-11/matplotlib/scatterplots/slug.csv
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2001-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2001-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2001-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2001-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2001-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2001-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2002-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2003-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2004-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2005-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2006-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2007-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2008-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2009-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2010-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2011-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2012-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2013-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-August.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-December.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-July.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-June.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-November.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-October.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2014-September.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2015-April.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2015-February.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2015-January.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2015-March.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/2015-May.txt.gz
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/list.waikato.ac.nz/pipermail/wekalist/index.html
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/plot_days.py
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/plot_hours.py
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/plot_months.py
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/plot_weekday.py
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/raw.csv
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/raw.py
 create mode 100644 docs/2015/2015-05-11/matplotlib/wekalist/wget.txt
 create mode 100644 docs/2015/2015-06-08/index.html
 create mode 100644 docs/2015/2015-07-13/ian/messagebox_demo.py
 create mode 100644 docs/2015/2015-07-13/ian/themed_toolkit_demo.py
 create mode 100644 docs/2015/2015-07-13/index.html
 create mode 100644 docs/2015/2015-08-10/index.html
 create mode 100644 docs/2015/2015-09-14/cadence_hampug_demo.py
 create mode 100644 docs/2015/2015-09-14/index.html
 create mode 100644 docs/2015/2015-09-14/loadscript.py
 create mode 100644 docs/2015/2015-10-12/begins/begins.py
 create mode 100644 docs/2015/2015-10-12/begins/begins_additional.py
 create mode 100644 docs/2015/2015-10-12/begins/begins_mult.py
 create mode 100644 docs/2015/2015-10-12/begins/index.html
 create mode 100644 docs/2015/2015-10-12/begins/oldfashioned.py
 create mode 100644 docs/2015/2015-10-12/index.html
 create mode 100644 docs/2015/2015-10-12/plac/index.html
 create mode 100644 docs/2015/2015-10-12/quiz/index.html
 create mode 100644 docs/2015/2015-10-12/sys.argv/index.html
 create mode 100644 docs/2015/2015-11-09/index.html
 create mode 100644 docs/2015/2015-11-09/pelican/Pelican/index.html
 create mode 100644 docs/2015/2015-11-09/pyudev/index.html
 create mode 100644 docs/2015/2015-11-09/pyudev/pyudev_demo_1.py
 create mode 100644 docs/2015/2015-11-09/pyudev/pyudev_demo_2.py
 create mode 100644 docs/2015/2015-11-09/pyudev/pyudev_demo_3.py
 create mode 100644 docs/2015/2015-11-09/pyudev/pyudev_demo_4.py
 create mode 100644 docs/2015/2015-12-14/01_demo_get_pin.py
 create mode 100644 docs/2015/2015-12-14/02_demo_rpi_package.py
 create mode 100644 docs/2015/2015-12-14/03_demo_ttk_1_led.py
 create mode 100644 docs/2015/2015-12-14/04_demo_ttk_4_led_counter_simple.py
 create mode 100644 docs/2015/2015-12-14/05_demo_ttk_4_led_counter_complex.py
 create mode 100644 docs/2015/2015-12-14/06_demo_ttk_4_led_counter_inc_dec.py
 create mode 100644 docs/2015/2015-12-14/07_demo_ttk_2_switches.py
 create mode 100644 docs/2015/2015-12-14/08_demo_ttk_pwm_linear.py
 create mode 100644 docs/2015/2015-12-14/09_demo_ttk_pwm_exponential.py
 create mode 100644 docs/2015/2015-12-14/RPi.GPIO Circuit Diagram.pdf
 create mode 100644 docs/2015/2015-12-14/index.html
 create mode 100644 docs/2015/index.html
 create mode 100644 docs/2016/2016-02-08/index.html
 create mode 100644 docs/2016/2016-03-14/index.html
 create mode 100644 docs/2016/2016-03-14/irsbugs/06_demo_ttk_4_led_counter_inc_dec.py
 create mode 100644 docs/2016/2016-03-14/irsbugs/09_demo_ttk_pwm_exponential.py
 create mode 100644 docs/2016/2016-03-14/irsbugs/nikola-march.svg
 create mode 100644 docs/2016/2016-03-14/irsbugs/pythonhouse-2016-03-14.py
 create mode 100644 docs/2016/2016-04-11/index.html
 create mode 100644 docs/2016/2016-04-11/ncea presentation/circle_1.py
 create mode 100644 docs/2016/2016-04-11/ncea presentation/circle_2.py
 create mode 100644 docs/2016/2016-04-11/ncea presentation/circle_3.py
 create mode 100644 docs/2016/2016-04-11/ncea presentation/circle_3a.py
 create mode 100644 docs/2016/2016-04-11/ncea presentation/circle_4.py
 create mode 100644 docs/2016/2016-04-11/ncea presentation/circle_5.py
 create mode 100644 docs/2016/2016-04-11/ncea presentation/index.html
 create mode 100644 docs/2016/2016-04-11/prime_number/index.html
 create mode 100644 docs/2016/2016-04-11/prime_number/prime_number_locater.py
 create mode 100644 docs/2016/2016-04-11/prime_number/prime_number_locater_flow.txt
 create mode 100644 docs/2016/2016-04-11/prime_number/prime_number_locater_help.txt
 create mode 100644 docs/2016/2016-04-11/prime_number/prime_number_locater_minimal_recursion.py
 create mode 100644 docs/2016/2016-04-11/prime_number/prime_number_locater_reference.txt
 create mode 100644 docs/2016/2016-04-11/prime_number/prime_number_locater_specification.txt
 create mode 100644 docs/2016/2016-04-11/prime_number/prime_number_rabinmiller.py
 create mode 100644 docs/2016/2016-05-09/index.html
 create mode 100644 docs/2016/2016-05-09/python2to3experiences/python2python3.pdf
 create mode 100644 docs/2016/2016-05-09/python2to3experiences/python2to3migration/index.html
 create mode 100644 docs/2016/2016-06-13/index.html
 create mode 100644 docs/2016/2016-07-11/index.html
 create mode 100644 docs/2016/2016-08-08/index.html
 create mode 100644 docs/2016/2016-08-08/nikola.pdf
 create mode 100644 docs/2016/2016-09-12/ian-python_art/circle_1.py
 create mode 100644 docs/2016/2016-09-12/ian-python_art/circle_2.py
 create mode 100644 docs/2016/2016-09-12/ian-python_art/circle_3.py
 create mode 100644 docs/2016/2016-09-12/ian-python_art/circle_4.py
 create mode 100644 docs/2016/2016-09-12/ian-python_art/index.html
 create mode 100644 docs/2016/2016-09-12/ian-tkinter_templates/circle.py
 create mode 100644 docs/2016/2016-09-12/ian-tkinter_templates/circle_initial.py
 create mode 100644 docs/2016/2016-09-12/ian-tkinter_templates/index.html
 create mode 100644 docs/2016/2016-09-12/index.html
 create mode 100644 docs/2016/2016-10-10/index.html
 create mode 100644 docs/2016/2016-11-14/flask/flask.svg
 create mode 100644 docs/2016/2016-11-14/index.html
 create mode 100644 docs/2016/2016-11-14/tesla/teslaapi.svg
 create mode 100644 docs/2016/2016-11-14/web2py/index.html
 create mode 100644 docs/2016/2016-11-14/web2py/meetup.py
 create mode 100644 docs/2016/2016-12-13/index.html
 create mode 100644 docs/2016/index.html
 create mode 100644 docs/2017/2017-02-13/index.html
 create mode 100644 docs/2017/2017-03-13/django.pdf
 create mode 100644 docs/2017/2017-03-13/django.tar.gz
 create mode 100644 docs/2017/2017-03-13/index.html
 create mode 100644 docs/2017/2017-04-10/ian/index.html
 create mode 100644 docs/2017/2017-04-10/index.html
 create mode 100644 docs/2017/2017-05-08/ian-client-server/gtk_client.py
 create mode 100644 docs/2017/2017-05-08/ian-client-server/index.html
 create mode 100644 docs/2017/2017-05-08/ian-client-server/server.py
 create mode 100644 docs/2017/2017-05-08/ian-google-talk/google_talk_presentation.tar.gz
 create mode 100644 docs/2017/2017-05-08/ian-google-talk/index.html
 create mode 100644 docs/2017/2017-05-08/index.html
 create mode 100644 docs/2017/2017-05-08/ldo-generators-coroutines-asyncio/collatz_generator
 create mode 100644 docs/2017/2017-05-08/ldo-generators-coroutines-asyncio/connections.svg
 create mode 100644 docs/2017/2017-05-08/ldo-generators-coroutines-asyncio/coro_try1.py
 create mode 100644 docs/2017/2017-05-08/ldo-generators-coroutines-asyncio/coro_try2
 create mode 100644 docs/2017/2017-05-08/ldo-generators-coroutines-asyncio/hailstone.py
 create mode 100644 docs/2017/2017-05-08/ldo-generators-coroutines-asyncio/iter123.py
 create mode 100644 docs/2017/2017-05-08/ldo-generators-coroutines-asyncio/notes.txt
 create mode 100644 docs/2017/2017-05-08/ldo-generators-coroutines-asyncio/rocket_launch_with_callbacks
 create mode 100644 docs/2017/2017-05-08/ldo-generators-coroutines-asyncio/rocket_launch_with_coroutines
 create mode 100644 docs/2017/2017-05-08/ldo-generators-coroutines-asyncio/yield_expression
 create mode 100644 docs/2017/2017-06-12/index.html
 create mode 100644 docs/2017/2017-07-10/index.html
 create mode 100644 docs/2017/2017-08-10/index.html
 create mode 100644 docs/2017/2017-09-11/index.html
 create mode 100644 docs/2017/2017-09-11/ldo/daily_usage
 create mode 100644 docs/2017/2017-09-11/ldo/loader
 create mode 100644 docs/2017/2017-09-11/ldo/notes.txt
 create mode 100644 docs/2017/2017-09-11/ldo/plot_daily_usage
 create mode 100644 docs/2017/2017-09-11/ldo/plot_period_usage
 create mode 100644 docs/2017/2017-10-09/ian/client_test.py
 create mode 100644 docs/2017/2017-10-09/ian/index.html
 create mode 100644 docs/2017/2017-10-09/ian/server_test.py
 create mode 100644 docs/2017/2017-10-09/index.html
 create mode 100644 docs/2017/2017-10-09/ldo/Processes, Threads, Coroutines.ogv
 create mode 100644 docs/2017/2017-10-09/ldo/notes.txt
 create mode 100644 docs/2017/2017-11-13/index.html
 create mode 100644 docs/2017/2017-12-11/index.html
 create mode 100644 docs/2017/index.html
 create mode 100644 docs/2018/2018-02-12/index.html
 create mode 100644 docs/2018/2018-02-12/setuptools_pypi_mkdocs/PyFunk.tar.gz
 create mode 100644 docs/2018/2018-03-12/ian/Setting up Python on Windows x64.pdf
 create mode 100644 docs/2018/2018-03-12/ian/Setting up Python on Windows x64.pptx
 create mode 100644 docs/2018/2018-03-12/ian/index.html
 create mode 100644 docs/2018/2018-03-12/index.html
 create mode 100644 docs/2018/2018-04-09/index.html
 create mode 100644 docs/2018/2018-04-09/ldo/module_decorator.py
 create mode 100644 docs/2018/2018-05-14/ian-jupiter/index.html
 create mode 100644 docs/2018/2018-05-14/ian-python-version/index.html
 create mode 100644 docs/2018/2018-05-14/index.html
 create mode 100644 docs/2018/2018-05-14/my_first_notebook/index.html
 create mode 100644 docs/2018/2018-06-11/cowsay.io.http
 create mode 100644 docs/2018/2018-06-11/index.html
 create mode 100644 docs/2018/2018-06-11/presentation.html
 create mode 100644 docs/2018/2018-06-11/presentation/index.html
 create mode 100644 docs/2018/2018-07-09/index.html
 create mode 100644 docs/2018/2018-08-13/index.html
 create mode 100644 docs/2018/2018-08-13/ldo-creating-api-bindings-using-ctypes/notes.txt
 create mode 100644 docs/2018/2018-08-13/ldo-creating-api-bindings-using-ctypes/spirotri.c
 create mode 100644 docs/2018/2018-08-13/ldo-creating-api-bindings-using-ctypes/spirotri.png
 create mode 100644 docs/2018/2018-08-13/ldo-creating-api-bindings-using-ctypes/spirotri_pyc
 create mode 100644 docs/2018/2018-08-13/ldo-creating-api-bindings-using-ctypes/spirotri_qah
 create mode 100644 docs/2018/2018-09-10/index.html
 create mode 100644 docs/2018/2018-09-10/waitress/index.html
 create mode 100644 docs/2018/2018-09-10/waitress/mysite.zip
 create mode 100644 docs/2018/2018-10-08/fifo/index.html
 create mode 100644 docs/2018/2018-10-08/index.html
 create mode 100644 docs/2018/2018-10-08/intel_distro/intel_distro.pdf
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/results_intelpython.txt
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/results_pythonorg.txt
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_01.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_02.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_03.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_04.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_05.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_11.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_12.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_13.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_14.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_15.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_16.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_17.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_21.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_22.py
 create mode 100644 docs/2018/2018-10-08/intel_distro/tests/test_23.py
 create mode 100644 docs/2018/2018-10-08/ldo-web-scraping/notes.txt
 create mode 100644 docs/2018/2018-11-12/index.html
 create mode 100644 docs/2018/2018-12-10/index.html
 create mode 100644 docs/2018/index.html
 create mode 100644 docs/2019/2019-02-11/django - install and get started.pdf
 create mode 100644 docs/2019/2019-02-11/index.html
 create mode 100644 docs/2019/2019-03-11/index.html
 create mode 100644 docs/2019/2019-03-11/local_bin/bin presentation.pdf
 create mode 100644 docs/2019/2019-03-11/local_bin/index.html
 create mode 100644 docs/2019/2019-03-11/rpi3_and_tensorflow/index.html
 create mode 100644 docs/2019/2019-03-11/rpi3_and_tensorflow/object_detection_webcam.py
 create mode 100644 docs/2019/2019-03-11/rpi3_and_tensorflow/tensorflow.pdf
 create mode 100644 docs/2019/2019-04-08/index.html
 create mode 100644 docs/2019/2019-05-13/conf_quiet.py
 create mode 100644 docs/2019/2019-05-13/index.html
 create mode 100644 docs/2019/2019-05-13/presentation_history
 create mode 100644 docs/2019/2019-06-10/bonobo/index.html
 create mode 100644 docs/2019/2019-06-10/bonobo/migrate.py
 create mode 100644 docs/2019/2019-06-10/bonobo/requirements.txt
 create mode 100644 docs/2019/2019-06-10/bubbles/index.html
 create mode 100644 docs/2019/2019-06-10/bubbles/migrate.py
 create mode 100644 docs/2019/2019-06-10/bubbles/requirements.txt
 create mode 100644 docs/2019/2019-06-10/data/index.html
 create mode 100644 docs/2019/2019-06-10/data/socialmedia.csv
 create mode 100644 docs/2019/2019-06-10/etl.pdf
 create mode 100644 docs/2019/2019-06-10/ian/index.html
 create mode 100644 docs/2019/2019-06-10/index.html
 create mode 100644 docs/2019/2019-06-10/pandas/index.html
 create mode 100644 docs/2019/2019-06-10/pandas/migrate.py
 create mode 100644 docs/2019/2019-06-10/pandas/requirements.txt
 create mode 100644 docs/2019/2019-06-10/petl/index.html
 create mode 100644 docs/2019/2019-06-10/petl/migrate.py
 create mode 100644 docs/2019/2019-06-10/petl/requirements.txt
 create mode 100644 docs/2019/2019-07-08/index.html
 create mode 100644 docs/2019/2019-07-08/jupyter_kernels/index.html
 create mode 100644 docs/2019/2019-07-08/pep484_type_hinting/index.html
 create mode 100644 docs/2019/2019-07-08/pep484_type_hinting/simple.py
 create mode 100644 docs/2019/2019-08-12/index.html
 create mode 100644 docs/2019/index.html
 create mode 100644 docs/404.html
 create mode 100644 docs/css/base.css
 create mode 100644 docs/css/bootstrap-custom.min.css
 create mode 100644 docs/css/font-awesome.min.css
 create mode 100644 docs/fonts/fontawesome-webfont.eot
 create mode 100644 docs/fonts/fontawesome-webfont.svg
 create mode 100644 docs/fonts/fontawesome-webfont.ttf
 create mode 100644 docs/fonts/fontawesome-webfont.woff
 create mode 100644 docs/fonts/fontawesome-webfont.woff2
 create mode 100644 docs/fonts/glyphicons-halflings-regular.eot
 create mode 100644 docs/fonts/glyphicons-halflings-regular.svg
 create mode 100644 docs/fonts/glyphicons-halflings-regular.ttf
 create mode 100644 docs/fonts/glyphicons-halflings-regular.woff
 create mode 100644 docs/fonts/glyphicons-halflings-regular.woff2
 create mode 100644 docs/img/favicon.ico
 create mode 100644 docs/img/grid.png
 create mode 100644 docs/index.html
 create mode 100644 docs/js/base.js
 create mode 100644 docs/js/bootstrap-3.0.3.min.js
 create mode 100644 docs/js/jquery-1.10.2.min.js
 create mode 100644 docs/mkdocs-auto
 create mode 100644 docs/search/lunr.js
 create mode 100644 docs/search/main.js
 create mode 100644 docs/search/search_index.json
 create mode 100644 docs/search/worker.js
 create mode 100644 docs/sitemap.xml
 create mode 100644 docs/sitemap.xml.gz
returncode: 0
Username for 'https://github.com': irsbugs
Password for 'https://irsbugs@github.com': 
Counting objects: 266, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (224/224), done.
Writing objects: 100% (266/266), 842.77 KiB | 4.11 MiB/s, done.
Total 266 (delta 110), reused 0 (delta 0)
remote: Resolving deltas: 100% (110/110), completed with 1 local object.
To https://github.com/irsbugs/meetings.git
   a111917..bc28c71  master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
returncode: 0
(venv7) ian@X200:~/hampug-website/meetings$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
(venv7) ian@X200:~/hampug-website/meetings$ 
"""

